platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

def shared_pods
  #pod 'Alamofire' 
  #pod 'SwiftyJSON'
  pod 'MJRefresh'
  pod "SnapKit"
  #pod 'Kingfisher'
  #pod 'SVProgressHUD'
  pod 'MBProgressHUD'
  
  #pod 'SDCycleScrollView','~> 1.3'
  #pod 'APParallaxHeader'
  #pod 'RoundImageView', '~> 1.0.1'
  #pod 'StrechyParallaxScrollView', '~> 0.1'
  #pod 'TextFieldEffects'
  #pod 'IQKeyboardManagerSwift'
  #pod 'Validator'
  #pod 'Qiniu', '~> 7.0'
  #pod 'Google-Mobile-Ads-SDK', '~> 7.0'
end

target 'swiftFactory' do
shared_pods
end

